/**
 * @author 
 *
 *   /\_/\  _     ___
 *  |>'v'<||"| -/\, ,`>
 *     -=Edelstein=-
 * 
 */
public class mainGUI extends javax.swing.JFrame {
    //stable variables
    int currentQuestionNumber;
    int selectedAnswer;
    int score;
    double scorePercent;
    
    final String[] QUESTIONS = {"0", "What is the best class in maplestory", "What is the best minecraft modpack?", "What is best linux distro?", "Who is the best pet?", "What is the worst language?"};
   
    final String[] RESPONSES_ONE   = {"Hayato", "Blaster", "Mikhail", "Adele"};
    final String[] RESPONSES_TWO   = {"Ultimate Alchemy", "Skyfactory(1-4)", "Tekkit", "Enegmatic6"};
    final String[] RESPONSES_THREE = {"Gentoo", "Ubuntu", "Arch", "Amog-os"};
    final String[] RESPONSES_FOUR  = {"Kino", "Mir", "Chester", "Shadow Key"};
    final String[] RESPONSES_FIVE  = {"Java", "Java", "Java", "JavaScript/Java"};
    
    final int[] ANSWERS = {5, 1, 1, 1, 1, 1, 5};
    
    public mainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        choiceD = new javax.swing.JButton();
        choiceB = new javax.swing.JButton();
        choiceC = new javax.swing.JButton();
        choiceA = new javax.swing.JButton();
        responseA = new javax.swing.JLabel();
        responseB = new javax.swing.JLabel();
        responseC = new javax.swing.JLabel();
        responseD = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        currentQuestion = new javax.swing.JLabel();
        questionNumber = new javax.swing.JLabel();
        currentlySelected = new javax.swing.JLabel();
        rightOrWrong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        submitButton.setText("submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel1.setText("Max's quiz!");

        jLabel7.setText("Simply select your answer below,");

        jLabel8.setText("and press submit!");

        choiceD.setText("D");
        choiceD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceDActionPerformed(evt);
            }
        });

        choiceB.setText("B");
        choiceB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceBActionPerformed(evt);
            }
        });

        choiceC.setText("C");
        choiceC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceCActionPerformed(evt);
            }
        });

        choiceA.setText("A");
        choiceA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceAActionPerformed(evt);
            }
        });

        responseA.setText("    ");

        responseB.setText("    ");

        responseC.setText("    ");

        responseD.setText("    ");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        currentQuestion.setText("question");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentQuestion)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentQuestion)
                .addContainerGap())
        );

        questionNumber.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        questionNumber.setText("Start the quiz!");

        currentlySelected.setText("   ");

        rightOrWrong.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(choiceA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(choiceB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(choiceC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(choiceD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(responseC)
                                    .addComponent(responseA))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(responseD)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(responseB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rightOrWrong)
                                        .addGap(14, 14, 14))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(questionNumber)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(57, 57, 57)
                                            .addComponent(jLabel1))
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(jLabel8))))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(submitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(currentlySelected)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(21, 21, 21)
                .addComponent(currentlySelected)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(choiceA)
                            .addComponent(choiceB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(choiceC)
                            .addComponent(choiceD)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(questionNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(responseA)
                            .addComponent(responseB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(rightOrWrong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(responseC)
                    .addComponent(responseD))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choiceAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceAActionPerformed
        //setting selections(for choiceA-DActionPreformed)
        selectedAnswer = 1;
        currentlySelected.setText(String.valueOf("You selected: A"));
    }//GEN-LAST:event_choiceAActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //add score
        if(selectedAnswer == ANSWERS[currentQuestionNumber]){
                score = score + 1;
                rightOrWrong.setText(String.valueOf("correct!"));
            } else{
            rightOrWrong.setText(String.valueOf("wrong!"));
        }
        if(currentQuestionNumber == 0){
            rightOrWrong.setText(String.valueOf(""));
        }
        
        
        //quiz finished
        if(currentQuestionNumber >= 5){
            //stopping stuff from working
            currentQuestionNumber = 6;
            
            //rounding
            scorePercent = (double)score/5*100;
            scorePercent = scorePercent*100;
            scorePercent = Math.round(scorePercent);
            scorePercent = scorePercent / 100;
             
            //gui cleanup
            responseA.setText(String.valueOf(""));
            responseB.setText(String.valueOf(""));
            responseC.setText(String.valueOf(""));
            responseD.setText(String.valueOf(""));
            rightOrWrong.setText(String.valueOf(""));
            
            questionNumber.setText(String.valueOf("Finished!"));
            currentQuestion.setText(String.valueOf("You finished the quiz! You got: " + score + "/5! %" + scorePercent));
        } 
        
        //quiz continued
        else{
                //next question
            currentQuestionNumber = currentQuestionNumber + 1;
            questionNumber.setText(String.valueOf("Question " + currentQuestionNumber + ":"));
            currentQuestion.setText(String.valueOf(QUESTIONS[currentQuestionNumber]));

            //output questions
            if(currentQuestionNumber == 1){
                responseA.setText(String.valueOf(RESPONSES_ONE[0]));
                responseB.setText(String.valueOf(RESPONSES_ONE[1]));
                responseC.setText(String.valueOf(RESPONSES_ONE[2]));
                responseD.setText(String.valueOf(RESPONSES_ONE[3]));
            } else if(currentQuestionNumber == 2){
                responseA.setText(String.valueOf(RESPONSES_TWO[0]));
                responseB.setText(String.valueOf(RESPONSES_TWO[1]));
                responseC.setText(String.valueOf(RESPONSES_TWO[2]));
                responseD.setText(String.valueOf(RESPONSES_TWO[3]));
            } else if(currentQuestionNumber == 3){
                responseA.setText(String.valueOf(RESPONSES_THREE[0]));
                responseB.setText(String.valueOf(RESPONSES_THREE[1]));
                responseC.setText(String.valueOf(RESPONSES_THREE[2]));
                responseD.setText(String.valueOf(RESPONSES_THREE[3]));
            } else if(currentQuestionNumber == 4){
                responseA.setText(String.valueOf(RESPONSES_FOUR[0]));
                responseB.setText(String.valueOf(RESPONSES_FOUR[1]));
                responseC.setText(String.valueOf(RESPONSES_FOUR[2]));
                responseD.setText(String.valueOf(RESPONSES_FOUR[3]));
            } else if(currentQuestionNumber == 5){
                responseA.setText(String.valueOf(RESPONSES_FIVE[0]));
                responseB.setText(String.valueOf(RESPONSES_FIVE[1]));
                responseC.setText(String.valueOf(RESPONSES_FIVE[2]));
                responseD.setText(String.valueOf(RESPONSES_FIVE[3]));
            } else{
                responseA.setText(String.valueOf(""));
                responseB.setText(String.valueOf(""));
                responseC.setText(String.valueOf(""));
                responseD.setText(String.valueOf(""));
            }
        }    
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void choiceBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceBActionPerformed
        selectedAnswer = 2;
        currentlySelected.setText(String.valueOf("You selected: B"));
    }//GEN-LAST:event_choiceBActionPerformed

    private void choiceCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceCActionPerformed
        selectedAnswer = 3;
        currentlySelected.setText(String.valueOf("You selected: C"));
    }//GEN-LAST:event_choiceCActionPerformed

    private void choiceDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceDActionPerformed
        selectedAnswer = 4;
        currentlySelected.setText(String.valueOf("You selected: D"));
    }//GEN-LAST:event_choiceDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choiceA;
    private javax.swing.JButton choiceB;
    private javax.swing.JButton choiceC;
    private javax.swing.JButton choiceD;
    private javax.swing.JLabel currentQuestion;
    private javax.swing.JLabel currentlySelected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel questionNumber;
    private javax.swing.JLabel responseA;
    private javax.swing.JLabel responseB;
    private javax.swing.JLabel responseC;
    private javax.swing.JLabel responseD;
    private javax.swing.JLabel rightOrWrong;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
